# 监听配置
listen-address=127.0.0.1,192.168.0.36
bind-interfaces

# 上游 DNS
server=223.5.5.5
server=223.6.6.6
server=119.29.29.29

# 缓存优化
cache-size=10000
dns-forward-max=1000
min-cache-ttl=300
neg-ttl=3600

# 不读取 resolv.conf
no-resolv
no-poll

# 日志
log-facility=-
log-queries
